# Get Composer cache
- name: Get Composer Cache Directory
  id: composer-cache
  run: |
    echo "::set-output name=dir::$(composer config cache-files-dir)"
- uses: actions/cache@v1
  with:
    path: ${{ steps.composer-cache.outputs.dir }}
    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    restore-keys: |
      ${{ runner.os }}-composer-

# Get Composer Dependencies
- name: Get Composer Dependencies
  uses: pxgamer/composer-action@master
  with:
    command: install --no-dev --optimize-autoloader --prefer-dist
