on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Stage Framework

jobs:
  build:
    name: Get deps & zip
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout code
        uses: actions/checkout@v2

      # Composer action
      - uses: ./.github/actions/composer

      # Yarn action
      - uses: ./.github/actions/yarn

      # ZIP Release
      - uses: ./.github/actions/zip

      # Create Release with Upload & Changelog
      - uses: ./.github/actions/release
