name: Create Release Archive
on: [push]
jobs:
  build:
    name: Get deps & zip
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@master
      # Following steps reference actions.
      - name: Get Composer Dependencies
        uses: pxgamer/composer-action@master
        with:
          command: install --no-dev --optimize-autoloader --prefer-dist
      - name: Get Yarn and compile assets
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --ignore-optional
      - run: yarn build:production
      - name: ZIP Release
        uses: thedoctor0/zip-release@master
        with:
          path: '.'
          filename: 'stage-installable.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./stage-installable.zip
          draft: true
