on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Stage Release

jobs:
  build:
    name: Get deps & zip
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout code
        uses: actions/checkout@v2
      # Get & Compile Composer & NPM assets
      - name: Get Composer Dependencies
        uses: pxgamer/composer-action@master
        with:
          command: install --no-dev --optimize-autoloader --prefer-dist
      - name: Get Yarn and compile assets
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --ignore-optional
      - run: yarn build:production
      # Build Release Zip
      - name: ZIP Release
        uses: thedoctor0/zip-release@master
        with:
          path: '.'
          filename: 'stage.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      # Create GitHub Release
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ # v1.0.0 tag
          prerelease_regex: "^v[[:digit:]]+\.[[:digit:]]+$" # v1.0 tag as pre-releases!
          create_draft: true
          update_existing: true
          created_tag: true
          release_title: ${{ github.ref }} is on Stage
          changelog_file: 'Changelog.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # One ZIP upload directly to Release
      - name: Upload Releases I
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'stage.zip'
          release-tag: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
